### ISSUE TITLE
weibo data

### ISSUE THREAD

**Issue by xiaoshengjun** [RowitZou/CG-nAR#3]
hello, I run the file "bash src/weibo_preprocess.sh", and find the command "python src/preprocess/construct_graph/weibo_graph/adj_feature.py",  the first function is open "resource/graph_data/weibo_graph/weibo-graph.txt", but the file is not find. 
Could you tell me how to get this file? 
Thank you!

**Comment by RowitZou** [comment]
Following README instructions, you can download data from https://pan.baidu.com/s/1awh3_ojU2AN4V536UINp0w, extraction code: kbiz
