### ISSUE TITLE
Responses generated by the model seem to have many incomplete sentences and incorrect grammar.

### ISSUE THREAD

**Issue by 27182812** [RowitZou/CG-nAR#4]
Hello, I find responses generated by the model seem to have many incomplete sentences and incorrect grammar. Is it the reason for non-autoregressive decoding?  Can it be solved by adjusting parameters?

**Comment by RowitZou** [comment]
Here are two solutions to improve the generation quality:

1. You could train insertion-TF with more sampled subsequences. See src/models/model.py line 557-558. 
2. Replace vanilla transformer with BERT. Just add two arguments to the training command: "-encoder BERT -sep_optim"

**Comment by 27182812** [comment]
Thank for your reply! Does it mean I need to add args.bert_dir and download the weight of Bert model. Does more sampled subsequences depond on the graph construction?

**Comment by RowitZou** [comment]
1. args.bert_dir can be the official BERT path in huggingface, namely 'bert-base-uncased'. Or you can download it in the local directory.
2. We ensure that all concepts are included in the sampled subsequences, plus some randomly selected words in the target response. The subsequence can be regarded as a prompt and the insertion-TF learns to complete the response. Giving more sampled subsequences means insertion-TF can see more states of partial responses in training time. Another solution is to make sure that the subsequence only contains the concepts themselves, so insertion-TF learns to generate responses based on concepts from scratch.

**Comment by 27182812** [comment]
Yes, I did. Thank you for your reply. It's very helpful!
