### ISSUE TITLE
weibo dataset的graph_data问题

### ISSUE THREAD

**Issue by YBAgg** [RowitZou/CG-nAR#6]
想请教下weibo的数据是从哪里来的，还有weibo-graph.txt是怎么生成的，您是如何提取关键字的？

**Comment by YBAgg** [comment]
是否方便提供下关键词提取的方法，谢谢啦

**Comment by RowitZou** [comment]
weibo-graph是来自 Conversational graph grounded policy learning for open-domain conversation generation 一文中公开的数据集。
链接如下：
http://ir.hit.edu.cn/~jxu/jun_files/papers/cg-graph.txt.zip

**Comment by YBAgg** [comment]
> weibo-graph是来自 Conversational graph grounded policy learning for open-domain conversation generation 一文中公开的数据集。 链接如下： http://ir.hit.edu.cn/~jxu/jun_files/papers/cg-graph.txt.zip

感谢分享
