### ISSUE TITLE
How did you get file 'candi_keyword.txt'?

### ISSUE THREAD

**Issue by unknowed-ER** [RowitZou/CG-nAR#7]
You provide file 'src/preprocess/persona_process/convai2/candi_keyword.txt'. 
It's seem that this file is the topic keyword. 
How do you get file 'candi_keyword.txt'? 
How do I build this file if I use code to work with other datasets?

**Comment by RowitZou** [comment]
We follow the preprocessing from a previous work, which uses a rule-based method and PMI measuring to get keywords: 
https://github.com/squareRoot3/Target-Guided-Conversation
