### ISSUE TITLE
Something's wrong with weibo's preprocessing

### ISSUE THREAD

**Issue by LZQ-Y** [RowitZou/CG-nAR#9]
After preprocessing raw data to json data, I got some .json documents with following contents:
![image](https://user-images.githubusercontent.com/109722423/184337231-f966fb17-8da0-4cc3-a6db-b4fa2b9fdc6d.png)

The problem is that there are no elements for "source_entity", "target_entity", "triples" and "context_keywords_list". I wonder why that happened because there's nothing wrong with persona's preprocessing.

**Comment by LzhinFdu** [comment]
> After preprocessing raw data to json data, I got some .json documents with following contents: ![image](https://user-images.githubusercontent.com/109722423/184337231-f966fb17-8da0-4cc3-a6db-b4fa2b9fdc6d.png)
> 
> The problem is that there are no elements for "source_entity", "target_entity", "triples" and "context_keywords_list". I wonder why that happened because there's nothing wrong with persona's preprocessing.

The reason may be that there are no correct graph-related data in "graph_data/weibo/". We need "vertex.txt", "adj_matrix.txt" and "weibo_graph_embedding.npy" in total before preprocessing raw data to json data. You can try running the steps in "weibo_preprocess.sh" step by step to make sure that all graph-related data is properly stored in this directory.
